const GAME_NAME = "berdly.com";
const GAME_VERSION = "1.0.27";

const CACHE_NAME = JSON.stringify({"name": GAME_NAME, "version": GAME_VERSION});
const CACHE_FILES = [
  "runner.data",
  "runner.js",
  "runner.wasm",
  "runner.worker.js",
  "audio-worklet.js",
  "index.js",
  "game.unx.part1",
  "game.unx.part2",
  "game.unx.part3",
  "game.unx.part4",
  "audio_intronoise.ogg",
  "audio_intronoise_ch1.ogg",
  "mus/acid_tunnel.ogg",
  "mus/alarm_titlescreen.ogg",
  "mus/alley_ambience.ogg",
  "mus/april_2012.ogg",
  "mus/audio_anotherhim.ogg",
  "mus/audio_darkness.ogg",
  "mus/audio_defeat.ogg",
  "mus/audio_drone.ogg",
  "mus/audio_story.ogg",
  "mus/basement.ogg",
  "mus/battle.ogg",
  "mus/berdly_audience.ogg",
  "mus/berdly_battle_heartbeat_true.ogg",
  "mus/berdly_chase.ogg",
  "mus/berdly_descend.ogg",
  "mus/berdly_flashback.ogg",
  "mus/berdly_theme.ogg",
  "mus/bird.ogg",
  "mus/boxing_boss.ogg",
  "mus/boxing_game.ogg",
  "mus/card_castle.ogg",
  "mus/castletown.ogg",
  "mus/castletown_empty.ogg",
  "mus/ch2_credits.ogg",
  "mus/charjoined.ogg",
  "mus/checkers.ogg",
  "mus/coolbeat.ogg",
  "mus/creepychase.ogg",
  "mus/creepydoor.ogg",
  "mus/creepylandscape.ogg",
  "mus/cyber.ogg",
  "mus/cyber_battle.ogg",
  "mus/cyber_battle_end.ogg",
  "mus/cyber_battle_prelude.ogg",
  "mus/cyber_shop.ogg",
  "mus/cybercity.ogg",
  "mus/cybercity_alt.ogg",
  "mus/cybercity_old.ogg",
  "mus/cyberhouse.ogg",
  "mus/cybershop_christmas.ogg",
  "mus/d.ogg",
  "mus/deep_noise.ogg",
  "mus/dogcheck.ogg",
  "mus/dontforget.ogg",
  "mus/elevator.ogg",
  "mus/fanfare.ogg",
  "mus/field_of_hopes.ogg",
  "mus/flashback_excerpt.ogg",
  "mus/forest.ogg",
  "mus/friendship.ogg",
  "mus/gallery.ogg",
  "mus/gameover_short.ogg",
  "mus/giant_queen_appears.ogg",
  "mus/gigaqueen_pre.ogg",
  "mus/hip_shop.ogg",
  "mus/home.ogg",
  "mus/honksong.ogg",
  "mus/joker.ogg",
  "mus/keygen.ogg",
  "mus/kingboss.ogg",
  "mus/lancer.ogg",
  "mus/lancer_susie.ogg",
  "mus/lancerfight.ogg",
  "mus/legend.ogg",
  "mus/man.ogg",
  "mus/mansion.ogg",
  "mus/mansion_entrance.ogg",
  "mus/menu.ogg",
  "mus/mus_birdnoise.ogg",
  "mus/mus_introcar.ogg",
  "mus/mus_school.ogg",
  "mus/muscle.ogg",
  "mus/music_guys.ogg",
  "mus/music_guys_intro.ogg",
  "mus/napsta_alarm.ogg",
  "mus/noelle.ogg",
  "mus/noelle_ferriswheel.ogg",
  "mus/noelle_normal.ogg",
  "mus/noelle_school.ogg",
  "mus/ocean.ogg",
  "mus/prejoker.ogg",
  "mus/queen.ogg",
  "mus/queen_boss.ogg",
  "mus/queen_car_radio.ogg",
  "mus/queen_intro.ogg",
  "mus/quiet_autumn.ogg",
  "mus/silence.ogg",
  "mus/rouxls_battle.ogg",
  "mus/ruruskaado.ogg",
  "mus/s_neo.ogg",
  "mus/s_neo_clip.ogg",
  "mus/shinkansen.ogg",
  "mus/shop1.ogg",
  "mus/sink_noise.ogg",
  "mus/spamton_basement.ogg",
  "mus/spamton_battle.ogg",
  "mus/spamton_happy.ogg",
  "mus/spamton_house.ogg",
  "mus/spamton_laugh_noise.ogg",
  "mus/spamton_meeting.ogg",
  "mus/spamton_meeting_intro.ogg",
  "mus/spamton_neo_after.ogg",
  "mus/spamton_neo_meeting.ogg",
  "mus/spamton_neo_mix_ex_wip.ogg",
  "mus/static_placeholder.ogg",
  "mus/tense.ogg",
  "mus/the_dark_truth.ogg",
  "mus/the_holy.ogg",
  "mus/thrash_rating.ogg",
  "mus/thrashmachine.ogg",
  "mus/town.ogg",
  "mus/tv_noise.ogg",
  "mus/vs_susie.ogg",
  "mus/w.ogg",
  "mus/wind.ogg",
  "mus/wind_highplace.ogg",
  "musb/battle_valley.ogg",
  "musb/bilingual-battle.ogg",
  "musb/boss_1.ogg",
  "musb/boss_2.ogg",
  "musb/cave.ogg",
  "musb/cave_fight.ogg",
  "musb/church_of_anime.ogg",
  "musb/code_shop.ogg",
  "musb/coffee_chat.ogg",
  "musb/duck.ogg",
  "musb/etal_valley.ogg",
  "musb/four_hour_workweek.ogg",
  "musb/interview_song_p1.ogg",
  "musb/interview_song_p2.ogg",
  "musb/interview_song_p3.ogg",
  "musb/interview_song_p4.ogg",
  "musb/line_dance.ogg",
  "musb/mega_lobotamy.ogg",
  "musb/mine_club.ogg",
  "musb/napstachords.ogg",
  "musb/nda_setter.ogg",
  "musb/nda_slammer.ogg",
  "musb/office.ogg",
  "musb/overworld.ogg",
  "musb/recruton.ogg",
  "musb/recruton_intro.ogg",
  "musb/silly_strings.ogg",
  "musb/silence.ogg",
  "musb/slides.ogg",
  "musb/slow_dance.ogg",
  "musb/stooxls.ogg",
  "musb/tima.ogg",
  "musb/timer.ogg",
  "musb/valley.ogg",
  "musb/valley_shop.ogg",
  "musb/valley_town.ogg",
  "musb/valley_town_b.ogg",
  "snd_bigcar_yelp.ogg",
  "snd_closet_fall.ogg",
  "snd_closet_fall_ch1.ogg",
  "snd_closet_impact.ogg",
  "snd_closet_impact_ch1.ogg",
  "snd_dtrans_drone.ogg",
  "snd_dtrans_flip.ogg",
  "snd_dtrans_heavypassing.ogg",
  "snd_dtrans_lw.ogg",
  "snd_dtrans_square.ogg",
  "snd_dtrans_twinkle.ogg",
  "snd_fountain_make.ogg",
  "snd_fountain_target.ogg",
  "snd_ghostappear.ogg",
  "snd_great_shine.ogg",
  "snd_great_shine_ch1.ogg",
  "snd_him_quick.ogg",
  "snd_hitcar.ogg",
  "snd_hitcar_little.ogg",
  "snd_icespell.ogg",
  "snd_jc_text.ogg",
  "snd_joel_text.ogg",
  "snd_keypress_2_ext.ogg",
  "snd_keypress_3_ext.ogg",
  "snd_keypress_4_ext.ogg",
  "snd_keypress_5_ext.ogg",
  "snd_mettaton_smash.ogg",
  "snd_mod_notif.ogg",
  "snd_mod_speak_double_low.ogg",
  "snd_mod_speak_double_low_echo.ogg",
  "snd_paper_rumble.ogg",
  "snd_paper_rumble_ch1.ogg",
  "snd_paper_surf.ogg",
  "snd_paper_surf_ch1.ogg",
  "snd_py_text.ogg",
  "snd_quack.ogg",
  "snd_revival.ogg",
  "snd_revival_ch1.ogg",
  "snd_rt_elevator_ding.ogg",
  "snd_rt_whistle.ogg",
  "snd_rurus_appear.ogg",
  "snd_rurus_appear_ch1.ogg",
  "snd_shoot_tima.ogg",
  "snd_smallcar_yelp.ogg",
  "snd_snowgrave.ogg",
  "snd_spell_pacify.ogg",
  "snd_straw_drink_long.ogg",
  "snd_text_tima.ogg",
  "snd_tick.ogg",
  "snd_tima_bell.ogg",
  "snd_tock.ogg",
  "snd_txteta.ogg",
  "snd_txtmod_1.ogg",
  "snd_txtmod_7.ogg",
  "snd_txtmod_9.ogg",
  "snd_usefountain.ogg",
  "snd_usefountain_ch1.ogg"
];

self.addEventListener("fetch", (event) => {
  const should_cache = CACHE_FILES.some((f) => {
      return event.request.url.endsWith(f);
  });
  event.respondWith(
    caches.match(event.request).then((resp) => {
      return resp || fetch(event.request).then((response) => {
        return caches.open(CACHE_NAME).then((cache) => {
          if (should_cache) {
            cache.put(event.request, response.clone());
          }
          return response;
        });
      });
    })
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.allSettled(
      keys.map((key) => {
        try {
          const data = JSON.parse(key);
          if (data && data["name"] && data.name == GAME_NAME &&
              data.version && data.version != GAME_VERSION) {
            return caches.delete(key);
          }
        } catch {
          return;
        }
      })
    )).then(() => {
    })
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});
